### ISSUE TITLE
Code for the nice dashbaords you have

### ISSUE THREAD

**Issue by giovannirco** [OliverHi/smarthomeserver#1]
It would be awesome if you can share the json files for the dashboards you have created :D 
I was looking for a quick way to check my temps on grafana instead of going to history tab of HA since I didnt finish setting up everything on the last weekend

**Comment by OliverHi** [comment]
Sorry, I think that is not super useful as the dashboard uses many specific sensor names that I have set up. However you can check out all my articles regarding that topic [here](https://thesmarthomejourney.com/tag/grafana/). I just recently explained my current setup [here](https://thesmarthomejourney.com/2022/07/07/grafana-rows/).
If you need information for specific panels in my dashboard let me know and I can share the code for that!
