### ISSUE TITLE
Preparing Grafana for sharing

### ISSUE THREAD

**Issue by donparlor** [OliverHi/smarthomeserver#2]
I did every configuration you suggested for Grafana:
<img width="405" alt="Capture d’écran, le 2022-08-07 à 10 50 36" src="https://user-images.githubusercontent.com/97048708/183296848-ab358228-bee0-4f57-9078-120ad5f3d787.png">
I also included those in the documentation of the add-on.

But I keep getting 401 Unauthorized view when trying to access my embedded graphs:

![297045271_386144540324650_6605440398211777314_n](https://user-images.githubusercontent.com/97048708/183297053-9bc11130-f484-45a6-a1b3-545a67f14419.jpg)

If I want to solve this, I must access the Web User Interface once, and now I get the graphs showing:
![296066502_1010007173021253_7697519921430684608_n](https://user-images.githubusercontent.com/97048708/183297136-336c0ef4-dd4b-4b5b-b389-616e3db2f2e1.jpg)

But this solution s temporary as long as my server is running. When rebooting HA, I will need to access Grafana Web User Interface again to display my graphs. 

Your help would be much appreciated

**Comment by OliverHi** [comment]
Hi, where did you add those configurations? You need to simply uncomment them [here](https://github.com/OliverHi/smarthomeserver/blob/76f1ac4d8fc687b365d71e18265e06a844ff3627/smarthome.yml#L27) to fix that issue

**Comment by donparlor** [comment]
> 

I added these configurations here:
<img width="405" alt="Capture d’écran, le 2022-08-07 à 10 50 36" src="https://user-images.githubusercontent.com/97048708/183310109-fe25ca0a-a278-4bac-bfbc-f23565c10b00.png">

Directly in the config tab of the add-on. Should I remove it and add Granada in my configurations.yaml?

**Comment by OliverHi** [comment]
I don't know what add-on you are talking about. This is a setup for running HA in a container and Grafana separately. If you are running HA OS with the supervisor you should check [here](https://github.com/hassio-addons/addon-grafana) or in the forums

**Comment by donparlor** [comment]
You are right Oliver, I'm not running HA in a container. I should have been more careful. I've been through documentation for HA Supervised / OS and I could find the solution. I hope it stands. Thank you for pointing me in the good direction. Wish you the best!

**Comment by OliverHi** [comment]
Glad to help! Could you maybe also share that solution here? Might help someone else fighting the same problem

**Comment by donparlor** [comment]
Following the online recommandations, I added the following env_vars in the Grafana add-on configuration 
```
- name: GF_AUTH_ANONYMOUS_ENABLED
  value: "true"
- name: GF_AUTH_DISABLE_LOGIN_FORM
  value: "false"
- name: GF_AUTH_ANONYMOUS_ORG_NAME
  value: Main Org.
- name: GF_AUTH_ANONYMOUS_ORG_ROLE
  value: Viewer
```

But it doesn't seem to work from a mobile access.... I'm still looking for a definitive solution for complete access with both local and remote access.

<img width="240" alt="Capture d’écran, le 2022-08-14 à 00 17 03" src="https://user-images.githubusercontent.com/97048708/184522276-0c52e31c-90d6-4a54-95fb-f3c6c6f1f5fe.png">

**Comment by OliverHi** [comment]
For now I will close this, if you ever find a solution for this please let me know

**Comment by donparlor** [comment]
I guess it's a "What the heck" type of problem... It's not working, I always need to access Grafana web interface to access my graphs from within HA.... It's sad....
